package com.techsetu.entity;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

import java.util.Date;

@Document(collection = "ai_sessions")
@Data
@NoArgsConstructor
@AllArgsConstructor
public class AiSession {
    @Id
    private String id;
    private Long userId;
    private String targetRole;
    private String interviewType; // "TECHNICAL" or "HR"
    private String language; // "ENGLISH", "HINDI", "HINGLISH"
    private Boolean active = true;
    private String feedbackSummary; // final evaluation generated by AI
    private Date createdAt = new Date();
}
